# Generated by Django 4.1.7 on 2023-04-10 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='rating',
            field=models.IntegerField(verbose_name='Rating'),
        ),
    ]
